# Generated by Django 5.2.11 on 2026-02-23 16:54

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name of brand')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='brand.jpg', upload_to='brand', verbose_name='brand')),
                ('start', models.DateTimeField(verbose_name='Start at')),
                ('end', models.DateTimeField(verbose_name='End at')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(default='category.jpg', upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Store name', max_length=255, verbose_name='name of store')),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('address', models.CharField(blank=True, default='Store adress', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='Store phone', max_length=255, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(default='yourmail@gmail.com', max_length=255, verbose_name='Email Address')),
                ('logo', models.ImageField(blank=True, default='', upload_to='store')),
                ('image1', models.ImageField(blank=True, default='image1', upload_to='store')),
                ('title1', models.CharField(blank=True, default='title1', max_length=50, null=True)),
                ('subtitle1', models.CharField(blank=True, default='subtitle1', max_length=50, null=True)),
                ('description1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image2', models.ImageField(blank=True, default='image2', upload_to='store')),
                ('title2', models.CharField(blank=True, default='title2', max_length=50, null=True)),
                ('subtitle2', models.CharField(blank=True, default='subtitle2', max_length=50, null=True)),
                ('description2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image3', models.ImageField(blank=True, default='image3', upload_to='store')),
                ('title3', models.CharField(blank=True, default='title3', max_length=50, null=True)),
                ('subtitle3', models.CharField(blank=True, default='subtitle3', max_length=50, null=True)),
                ('description3', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of product')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='old price')),
                ('image', models.ImageField(default='product.jpg', upload_to='product')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=False)),
                ('new_product', models.BooleanField(default=False)),
                ('featured_product', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='product.jpg', upload_to='product-images')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='app.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
