# Generated by Django 5.0 on 2023-12-13 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, default='', upload_to='categories/', verbose_name='Image')),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Store name', max_length=255, verbose_name='name of store')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='Store adress', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Phone')),
                ('email_address', models.EmailField(default='', max_length=255, verbose_name='Email Address')),
                ('logo', models.ImageField(blank=True, default='', upload_to='store/')),
                ('title1', models.CharField(blank=True, default='title1', max_length=50, null=True)),
                ('image1', models.ImageField(blank=True, default='', upload_to='store/')),
                ('title2', models.CharField(blank=True, default='title2', max_length=50, null=True)),
                ('image2', models.ImageField(blank=True, default='', upload_to='store/')),
                ('title3', models.CharField(blank=True, default='title3', max_length=50, null=True)),
                ('image3', models.ImageField(blank=True, default='', upload_to='store/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of product')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='informations about product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(blank=True, default='', upload_to='product/', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('show', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
            options={
                'verbose_name': 'Product',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PALNAlternatives', models.ManyToManyField(related_name='alternative_products', to='app.product', verbose_name='Alternatives')),
                ('PALNProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Alternative',
                'verbose_name_plural': 'Product Alternatives',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(blank=True, default='', upload_to='product/', verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=128, null=True, verbose_name='Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product images',
            },
        ),
    ]
