# Generated by Django 5.0 on 2023-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of product')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='product/', verbose_name='Image')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('end', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('show', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
    ]
