# Generated by Django 5.0 on 2026-02-17 04:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='about_us',
            field=ckeditor.fields.RichTextField(blank=True, default='About Us', null=True),
        ),
    ]
