# Generated by Django 5.0 on 2023-12-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_brand_end_alter_brand_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='productImage',
            new_name='image',
        ),
    ]
