# Generated by Django 5.0 on 2023-12-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_productimage_productimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='discount'),
            preserve_default=False,
        ),
    ]
