# Generated by Django 5.2.11 on 2026-03-02 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
