# Generated by Django 5.0 on 2023-12-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='email_address',
            new_name='email',
        ),
    ]
