# Generated by Django 5.0 on 2023-12-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_email_address_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='description', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(default='email', max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, default='Store phone', max_length=255, null=True, verbose_name='Contact Phone'),
        ),
    ]
