# Generated by Django 5.0 on 2023-12-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_store_description_alter_store_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(default='yourmail@gmail.com', max_length=255, verbose_name='Email Address'),
        ),
    ]
