# Generated by Django 5.0 on 2023-12-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description1',
            field=models.TextField(blank=True, default='description1', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description2',
            field=models.TextField(blank=True, default='description2', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description3',
            field=models.TextField(blank=True, default='description3', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subtitle1',
            field=models.CharField(blank=True, default='subtitle1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subtitle2',
            field=models.CharField(blank=True, default='subtitle2', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subtitle3',
            field=models.CharField(blank=True, default='subtitle3', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='image1',
            field=models.ImageField(blank=True, default='image1', upload_to='store/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image2',
            field=models.ImageField(blank=True, default='image2', upload_to='store/'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image3',
            field=models.ImageField(blank=True, default='image3', upload_to='store/'),
        ),
    ]
