# Generated by Django 5.0 on 2023-12-22 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_store_description1_store_description2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRELProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='app.product', verbose_name='Product')),
                ('PRelated', models.ManyToManyField(related_name='Related_products', to='app.product', verbose_name='Related products')),
            ],
            options={
                'verbose_name': 'Related Product',
                'verbose_name_plural': 'Related Products',
            },
        ),
        migrations.DeleteModel(
            name='ProductAlternative',
        ),
    ]
