# Generated by Django 5.2.11 on 2026-03-14 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
