# Generated by Django 5.0 on 2023-12-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_productsrelated_delete_productalternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.AddField(
            model_name='store',
            name='about_us',
            field=models.TextField(blank=True, default='About Us', null=True),
        ),
    ]
