# Generated by Django 5.2.11 on 2026-03-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productimages_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
