# Generated by Django 5.2.11 on 2026-03-15 11:37

import cloudinary.models
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_productimages_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Store name', max_length=255, verbose_name='name of store')),
                ('about_us', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('address', models.CharField(blank=True, default='Store adress', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default='Store phone', max_length=255, null=True, verbose_name='Contact Phone')),
                ('email', models.EmailField(default='mystore@gmail.com', max_length=255, verbose_name='Email Address')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo')),
                ('image1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image1')),
                ('title1', models.CharField(blank=True, default='title1', max_length=50, null=True)),
                ('subtitle1', models.CharField(blank=True, default='subtitle1', max_length=50, null=True)),
                ('description1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image2')),
                ('title2', models.CharField(blank=True, default='title2', max_length=50, null=True)),
                ('subtitle2', models.CharField(blank=True, default='subtitle2', max_length=50, null=True)),
                ('description2', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image3')),
                ('title3', models.CharField(blank=True, default='title3', max_length=50, null=True)),
                ('subtitle3', models.CharField(blank=True, default='subtitle3', max_length=50, null=True)),
                ('description3', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
            ],
        ),
        migrations.DeleteModel(
            name='Mystore',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'ordering': ['order', 'created'], 'verbose_name_plural': 'Product images'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
            preserve_default=False,
        ),
    ]
