# Generated by Django 5.2.11 on 2026-04-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_shop_city_shop_country_shop_is_closed_shop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
