# Generated by Django 5.2.11 on 2026-04-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_is_rejected_profile_is_validated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='shopvalidation',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='workinghours',
            name='is_closed',
        ),
    ]
