# Generated by Django 5.2.11 on 2026-03-17 22:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_store_delete_mystore_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-start_date'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='end',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='start',
        ),
        migrations.AddField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brand',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End at'),
        ),
        migrations.AddField(
            model_name='brand',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start at'),
        ),
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Name of brand'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(default='store@mail.com', max_length=255, verbose_name='Email Address'),
        ),
    ]
