# Generated by Django 5.2.11 on 2026-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_shop_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghours',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
