# Generated by Django 5.0 on 2024-02-14 21:25

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_productimages_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='old_price',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='This is the product', null=True, verbose_name='informations about product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=app.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image1',
            field=models.ImageField(blank=True, default='image1', upload_to='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image2',
            field=models.ImageField(blank=True, default='image2', upload_to='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='image3',
            field=models.ImageField(blank=True, default='image3', upload_to='store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='store'),
        ),
    ]
