# Generated by Django 5.2.11 on 2026-04-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_workinghours_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
