# Generated by Django 5.2.11 on 2026-04-05 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_shop_is_active_shop_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_active',
        ),
    ]
