# Generated by Django 5.0 on 2024-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_product_image_alter_product_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, default='brand.jpg', upload_to='brand', verbose_name='Brand'),
        ),
    ]
