"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ

env = environ.Env()
environ.Env.read_env()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5b)2xi-%m%0i=6ddd_6ugdz2ufzn_18u(&g&(8v@k7gs$n14_j'
# add SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','django-insecure-5b)2xi-%m%0i=6ddd_6ugdz2ufzn_18u(&g&(8v@k7gs$n14_j')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # False for deployement
# add DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'
# DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['127.0.0.1','oubaidphone.onrender.com'] 

# Application definition
INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
   
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # pip install whitenoise 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
'''
import dj_database_url
# Rener PostgreSQL database (Live)
# DATABASE_URL = "postgresql://postgres:-3CfBD3G62D4cg3def*5*AE1gcfDD5Bd@monorail.proxy.rlwy.net:25039/railway"
# DATABASES = {
#     'default': dj_database_url.config(default=DATABASE_URL,conn_max_age=1800),
# }


DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgressql',
            'NAME': 'oubaidphoneDatabase',
            'USER': 'oubaidphonedatabase_user',
            'PASSWORD': 'qsF4EBwwBroK0eqJA0GtbHhxTHgOdYNO',
            'HOST' : 'dpg-cm5kph21hbls73akb7q0-a',
            'PORT' : '5432',
        }}


'''
DATABASES = {
    'default': dj_database_url.parse(env('DATABASE_URL'))
}

'''

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles' 
# # STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATICFILES_DIRS = [
#     BASE_DIR / 'static'
# ]

# MEDIA_URL  = '/media/'
# MEDIA_ROOT= BASE_DIR / 'media/image'

# STATIC_URL = '/static/'

# MEDIA_URL = '/media/'

# STATIC_ROOT = BASE_DIR / 'staic'

# MEDIA_ROOT = BASE_DIR / 'media/images'

# STATICFILES_DIRS = [BASE_DIR / 'project/static']

STATIC_ROOT = os.path.join(BASE_DIR, 'static') # or 'staticfiles/'
STATIC_URL = '/static/'
# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'project/static')
] # and tap python manage.py collectstatic

# MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

## --------- add this code to project\urls --------------
# from django.contrib import admin
# from django.urls import path, include
# ==> from django.conf import settings
# ==> from django.conf.urls.static import static

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('app.urls')),
# ]

# ==> urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
# ==> urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# ==> Tap this command  python manage.py collectstatic
##-----------------------------------------------------------

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage' 


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# add 
'''
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=500,
        conn_health_checks=True,
    )
'''